inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6.6
  Exclude:
    - bin/bundle
    - bin/rails
    - bin/rake
    - bin/setup
    - bin/spring
    - bin/webpack
    - bin/webpack-dev-server
    - bin/yarn
    - config/boot.rb
    - config/spring.rb
    - config/puma.rb
    - config/environment.rb
    - config/environments/development.rb
    - config/environments/production.rb
    - config/environments/test.rb
    - config/initializers/wrap_parameters.rb
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - config.ru
    - Gemfile
    - Rakefile

# https://rubocop.readthedocs.io/en/latest/cops_style/#styleasciicomments
Style/AsciiComments:
  Enabled: false

# https://rubocop.readthedocs.io/en/latest/cops_style/#stylehasheachmethods
Style/HashEachMethods:
  Enabled: true

# https://rubocop.readthedocs.io/en/latest/cops_style/#stylehashtransformkeys
Style/HashTransformKeys:
  Enabled: true

# https://rubocop.readthedocs.io/en/latest/cops_style/#stylehashtransformvalues
Style/HashTransformValues:
  Enabled: true

# https://rubocop.readthedocs.io/en/latest/cops_style/#styleclassandmodulechildren
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/channels/application_cable/connection_test.rb'
    - 'test/test_helper.rb'

# https://rubocop.readthedocs.io/en/latest/cops_style/#styledocumentation
Style/Documentation:
  Enabled: false

# https://rubocop.readthedocs.io/en/latest/cops_style/#stylestringliterals
Style/StringLiterals:
  Exclude:
    - 'test/application_system_test_case.rb'
    - 'test/channels/application_cable/connection_test.rb'
    - spec/rails_helper.rb

# https://rubocop.readthedocs.io/en/latest/cops_layout/#layoutlinelength
Layout/LineLength:
  Max: 120

# https://rubocop.readthedocs.io/en/latest/cops_style/#stylefrozenstringliteralcomment
Style/FrozenStringLiteralComment:
  Exclude:
    - config/initializers/assets.rb
    - config/initializers/**/*

# https://rubocop.readthedocs.io/en/latest/cops_style/#styleblockcomments
Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

# https://rubocop.readthedocs.io/en/latest/cops_style/#stylesymbolarray
# Use EnforcedStyle: brackets
Style/SymbolArray:
  Enabled: false

# https://rubocop.readthedocs.io/en/latest/cops_metrics/#metricsblocklength
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecnestedgroups
RSpec/NestedGroups:
  Max: 5

# https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecmultipleexpectations
RSpec/MultipleExpectations:
  Max: 4

# https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecinstancevariable
RSpec/InstanceVariable:
  Enabled: false
